#Minecraft server properties
#Thu Feb 19 23:17:57 UTC 2026
allow-flight=true
allow-nether=false
announce-player-achievements=false
difficulty=1
enable-command-block=false
enable-query=false
enable-rcon=false
force-gamemode=false
gamemode=2
generate-structures=false
generator-settings=2;7,64x1,2;1;
hardcore=false
level-name=world
level-seed=-000000000000000000
level-type=FLAT
max-build-height=256
max-players=20
motd=A Redstropolis Server
online-mode=true
op-permission-level=4
player-idle-timeout=0
pvp=true
resource-pack=
server-ip=
server-port=25565
snooper-enabled=true
spawn-animals=false
spawn-monsters=false
spawn-npcs=false
view-distance=10
white-list=false